apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nicolaka-pod
  name: nicolaka-pod
spec:
  containers:
  - image: nicolaka/netshoot
    name: nicolaka-pod
    command: ['sh','-c','sleep 1d']
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
