apiVersion: v1
kind: Pod
metadata:
  name: sidecar-pod
spec:
  volumes:
  - name: sharedvol
    emptyDir: {} 
  containers:
  - image: ubuntu
    name: ubuntu-pod
    command: ['sh','-c','while true; do echo "jakies dane z aplikacji" >> /output/output.log; sleep 10 ; done']
    volumeMounts:
    - name: sharedvol
      mountPath: /output
  - image: busybox
    name: sidecar 
    command: ['sh', '-c', 'tail -F /input/output.log']
    volumeMounts:
    - name: sharedvol
      mountPath: /input
