apiVersion: v1
kind: Pod
metadata:
  labels:
    os: ubuntu22
  name: ubuntu-done
spec:
  containers:
  - image: ubuntu
    name: ubuntu-pod
  restartPolicy: Never
  dnsPolicy: ClusterFirst
status: {}
