apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
  - image: nginx
    name: web
    env:
      - name: MY_FIRST_ENVVAR
        value: mojawartosc
      - name: CONFIG
        valueFrom:
          configMapKeyRef:
            name: my-configmap
            key: config.json
    envFrom:
      - configMapRef: 
          name: mylastcm
