apiVersion: v1
kind: Pod
metadata:
  name: configmap-vol-pod
spec:
  volumes:
  - name: cmvol
    configMap:
      name: my-configmap
  containers:
  - image: nginx
    name: web
    volumeMounts:
      - name: cmvol
        mountPath: /data
