apiVersion: v1
kind: Pod
metadata:
  name: dynamic-pod
spec:
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: dynamic-pvc
  containers:
  - image: nginx
    name: web
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: data
