apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  key1: value1
  isImported: "true"
  version: "3.2"
  config.json: |
    { "attr1": "value1", 
      "attr2": "value2",
    }
  sshd_config: |
    Port 2222
