apiVersion: v1
kind: Pod
metadata:
  name: persistent-vol-pod
spec:
  nodeName: node1
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: my-pvc
  containers:
  - image: nginx
    name: web
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: data
