apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: secure-nginx
  name: secure-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: secure-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: secure-nginx
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: nginx-config
      - name: htpasswd-volume
        secret: 
          secretName: nginx-htpasswd
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx
        - name: htpasswd-volume
          mountPath: /etc/nginx/conf
