apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
spec:
  nodeName: node1
  containers:
  - image: nginx
    name: web
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: nfs-share
  volumes:
  - name: nfs-share
    nfs:
      server: 10.10.1.10
      path: /var/nfs-share
