apiVersion: v1
kind: Pod
metadata:
  name: toleration-pod
spec:
  containers:
  - image: nginx
    name: taint-test
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  tolerations:
  - key: "zone"
    operator: "Exists"
    effect: "NoSchedule"
status: {}
