apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: country
            operator: In
            values:
            - france
            - poland
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: storage
            operator: In
            values:
            - ssd
  containers:
  - name: with-node-affinity
    image: registry.k8s.io/pause:3.8
